4.	XHTML tagovi mogu imati jedan od sljedeca tri oblika: <ime atribut1=”vrijednost1” atribut2=”vrijednost2” ... > ili <ime /> 
(što je kraci nacin zapisivanja za <ime> ... </ime>) ili </ime> (koji oznacava kraj taga - završni tag). 
Primjeri tagova su: <img width=”200” height=”150” location=”slike.jpg” /> ili <h1 class=”headline”> 
Naslov </h1>. Karakteri <, > i / ne mogu se pojavljivati u imenima. Navodnici oko vrijednosti atributa su obavezni. 
Napisati FLEX datoteku koja ucitava XHTML datoteku i štampa je na standardni izlaz sa svim tagovima i atributima napisanim 
velikim slovima i sa prelaskom u novu liniju prije svakog pocetnog taga i poslije svakog završnog taga. Ostali tekst treba da bude 
isti kao u XHTML datoteci. 